getlift/lift

- src/components/Queues.ts
While testing the plugin, I encountered a weird issue when trying to access the URL of Lift-created Queue.
> Cannot resolve variable at "provider.environment.QUEUE_URL": Error: ${queues:myQueue.queueUrl} does not exist. Properties available on ${queues:myQueue} are: queueArn, queueUrl.
AFAICT `resolveVariable` will get in this case the string `myQueue.queueUrl` then when splitting `id` will be `myQueue` and `property` will be `queueUrl`.
So `property` should be used instead of `id` to check if this is a supported URL.
As a **very dirty workaround**, I called my queue `queueUrl` and it works when using `${queues:queueUrl.queueUrl}` :joy:
> Fix resolving queue URLs

- package-lock.json
- package.json
- src/components/StaticWebsite.ts
- test/unit/staticWebsites.test.ts
Recently there was a new concept added to CloudFront: cache policies.
These are supposed to replace how we configure what is cached and what isn't.
This PR upgrades to using cache policies. Per https://github.com/getlift/lift/discussions/5#discussioncomment-712809 recommendation, this allows to use Brotli compression for faster loading times.
On the implementation side: this allows for a simpler configuration, mostly because we switch to the new `Distribution` class instead of the older `CloudFrontWebDistribution` class. See https://stackoverflow.com/a/65933937/245552 for more details.
> Static website: upgrade to using cache policies

- README.md
- package-lock.json
- package.json
- src/plugin.ts
- src/types/serverless.ts
This PR adds a new `serverless lift eject` command. It also adds the related documentation.
This allows users to eject from Lift (to CloudFormation) easily.
Preview of the command:
> Add a command and documentation to eject from Lift

- .github/workflows/ci.yml
- src/constructs/Queue.ts
- src/constructs/StaticWebsite.ts
- src/constructs/Storage.ts
- src/plugin.ts
- src/utils/logger.ts
- test/fixtures/staticWebsites/public/scripts.js
- test/utils/runServerless.ts
- tsconfig.json
Current code base contains multiple eslint validation errors
```
/Users/Frederic/Sites/lift/src/plugin.ts
4:29   error    'json-schema' should be listed in the project's dependencies. Run 'npm i -S json-schema' to add it  import/no-extraneous-dependencies
77:39   error    Unsafe member access [configuration.type] on an `any` value                                         @typescript-eslint/no-unsafe-member-access
77:54   warning  Unexpected any. Specify a different type                                                            @typescript-eslint/no-explicit-any
92:19   error    Unsafe assignment of an `any` value                                                                 @typescript-eslint/no-unsafe-assignment
92:26   error    Unsafe member access [configuration.type] on an `any` …
```
> Improve schema validation logic

- docs/queue.md
- package-lock.json
- package.json
- src/classes/AwsProvider.ts
- src/classes/aws.ts
- src/constructs/Queue.ts
- src/constructs/queue/sqs.ts
- src/utils/sleep.ts
- test/unit/queues.test.ts
- test/unit/staticWebsites.test.ts
- test/utils/mockAws.ts
This PR enhances the `queue` construct with new CLI commands.
```
serverless <queue-construct>:failed
serverless <queue-construct>:failed:purge
serverless <queue-construct>:failed:retry
```
Read below for gifs and examples.
TODO:
Given this `serverless.yml` config:
```yaml
constructs:
jobs:
type: queue
worker:
handler: worker.handler
```
Users can now run:
```
serverless jobs:failed
```
This command will list messages from the dead letter queue. It will only attempt to fetch the first 30 messages (it wouldn't make sense to poll thousands of messages and dump them in the terminal).
https://user-images.githubusercontent.com/720328/121541663-cbefbc00-ca07-11eb-854b-cb7cd21da49d.mp4
```
serverless jobs:failed:purge
```
This command clears the dead letter queue.
```
serverless …
```
> Queue: add CLI commands to manage SQS dead letter queues

- docs/storage.md
- docs/webhook.md
Fixed typo in construct variables, removed the extra `s`.
This should fix #36.
> Fixed typo on “construct“ variables (fixes #36)

- README.md
- docs/webhook.md
Still trying each construct, I'm on the last: webhooks!
I copy/pasted the quick start to test webhooks and got an error:
```
TypeError: Cannot read property 'class' of undefined
at LiftPlugin.loadConstructs (/Users/afu/Workspaces/LiveCoding/Lift/4-webhook/node_modules/serverless-lift/dist/src/plugin.js:93:85)
at new LiftPlugin (/Users/afu/Workspaces/LiveCoding/Lift/4-webhook/node_modules/serverless-lift/dist/src/plugin.js:83:10)
at PluginManager.addPlugin (/Users/afu/Workspaces/LiveCoding/Lift/4-webhook/node_modules/serverless/lib/classes/PluginManager.js:112:28)
at /Users/afu/Workspaces/LiveCoding/Lift/4-webhook/node_modules/serverless/lib/classes/PluginManager.js:158:33
at Array.forEach (<anonymous>)
at PluginManager.loadAllPlugins …
```
> Added missing "type" configuration for webhooks

- src/plugin.ts
- src/types/serverless.ts
See for background https://github.com/serverless/serverless/issues/9610
Now when a variable fails to be resolved, the users see the actual error.
I think that could even be improved by using the `ServerlessError` class, but I have that in a separate branch for now.
Will add tests of variables separately from that.
> Implements the deprecated `variableResolvers` to make sure we display useful error messages to users

- src/constructs/StaticWebsite.ts
- src/plugin.ts
- src/utils/s3-sync.ts
- tsconfig.json
Use lodash flatten instead of Array.prototype.flat to fix the issue.
To prevent future issues, I lowered ts lib to match runtime requirements.
Fix: #38
> Fix node10 compatibility

- src/constructs/StaticWebsite.ts
- src/constructs/Webhook.ts
- src/plugin.ts
- src/utils/error.ts
Current Lift exceptions show as low-level errors in the CLI, and are reported as "programmer errors" in Telemetry:
I replaced using `throw new Error()` with using the `ServerlessError` class: this class ensures errors are better formatted in the CLI, and are reported as "user errors" in Telemetry:
Finally, I also tried to improve the existing user error messages to make them more actionable and helpful:
> Separate user errors from bugs in the CLI output and telemetry

- src/plugin.ts
- test/fixtures/permissions/serverless.yml
- test/unit/permissions.test.ts
Should fix https://github.com/getlift/lift/issues/47
Here we add to `provider.iam.role.statements` if it exists or add to `provider.iamRoleStatements` if not (so that we are still backward-compatible with older versions of the serverless framework.
TODO
> fix: allow to use the new provider.iam.role.statements

- src/CloudFormation.ts
- src/classes/AwsConstruct.ts
- src/classes/AwsProvider.ts
- src/classes/Construct.ts
- src/classes/index.ts
- src/constructs/Queue.ts
- src/constructs/StaticWebsite.ts
- src/constructs/Storage.ts
- src/constructs/Webhook.ts
- src/constructs/index.ts
- src/constructs/queue/sqs.ts
- src/plugin.ts
- src/types/serverless.ts
- src/utils/s3-sync.ts
This PR segregates code responsabilities across Lift code base. It introduces a few core concepts.
A construct is a class with:
- **Static members**, like `schema` and `type`, which are valid for all instances. Those static member can be seen as an API to the construct "catalog". When browsing existing constructs, you don't need to actually build one with the `new...` keyword, only need to access its static members.
- **Non-static members**, enforced via the `ConstructInterface`, exposing API to interact with a specific instance of this construct (i.e. `commands`, `outputs`, `references`)
Plugin entry point is responsible for:
- collecting all available schemas from the construct catalog (accessing static member of each Construct class)
- creating AwsProvider instance
- keeping an index …
> Move CDK logic to AwsProvider and implement factory logic for Construct build

- .github/workflows/ci.yml
- .github/workflows/release.yml
- package.json
This is PR adds a `prepare` script to the package.json.
This is a special npm script that is executed when installing a package from a git URL like so
```bash
npm install git@github.com:t-richard/lift.git#add-prepare-script
```
This would come in handy for the community to test WIP/draft constructs and is much more user-friendly than using `npm link`.
Previously, doing this would not work because we would be missing the `dist` folder in ` node_modules/serverless-lift`
The script behaviour is described at https://docs.npmjs.com/cli/v7/using-npm/scripts#life-cycle-scripts
It also says
> Runs BEFORE the package is published
This is why I also deleted `npm run build` from the release GH Action workflow
> Add npm prepare script

- .eslintignore
- .eslintrc
- src/classes/AwsConstruct.ts
- src/classes/AwsProvider.ts
- src/classes/Construct.ts
- src/constructs/Queue.ts
- src/constructs/StaticWebsite.ts
- src/constructs/Storage.ts
- src/constructs/Webhook.ts
- src/plugin.ts
- src/types/serverless.ts
- test/fixtures/variables/extra-plugin.js
- test/fixtures/variables/serverless.yml
- test/unit/common.test.ts
- test/unit/variables.test.ts
Fix #29.
Replaces #31.
On master:
- constructs are instantiated in the constructor of the Lift plugin
- that means that variables resolved _after_ the Lift plugin is instantiated are not resolved in constructs
In this branch:
- constructs are instantiated in the `initialize` hook (at this point, all variables are resolved)
- to achieve that, commands are now defined statically
- and Lift variables are resolved lazily using CDK tokens (CDK lazy variables)
This PR includes #41 (the test that reproduces the problem).
TODO:
> Instantiate constructs after all variables are resolved

- docs/static-website.md
- src/constructs/StaticWebsite.ts
- test/unit/staticWebsites.test.ts
At the moment, `static-website` redirects all 404 to `index.html`. This is perfect for SPA with routing in the browser (e.g. with react router or vue router): we want all unknown URLs to load the JS app.
However, this doesn't really work with flat static websites (without client-side routing).
This PR introduces a new `errorPage` option:
```yaml
constructs:
landing:
type: static-website
errorPage: error.html
```
- when not set, `static-website` is optimized for SPA and redirects 404s to `index.html` with a 200 response
- when set, 404s serve the error page (and keep a 404 response)
> Why go with the "SPA" behavior by default? Why not respond `404` responses by default?
The default error response for S3 is extremely ugly:
This cannot be considered a good "production-ready default". So the …
> [Static Website] Add new `errorPage` configuration

- src/classes/AwsConstruct.ts
- src/classes/AwsProvider.ts
- src/classes/Construct.ts
- src/constructs/Queue.ts
- src/constructs/StaticWebsite.ts
- src/constructs/Storage.ts
- src/constructs/Webhook.ts
- src/plugin.ts
On `master`, construct variables are defined as CloudFormation references (or "GetAtt"). These references are generated from CDK tokens, which come from CDK object properties.
Since we already resolve all CDK tokens that appear in `serverless.yml`, we can skip some work and use the CDK variables directly.
Why:
- CDK constructs are simpler to write, and simpler to reason about
- importing existing CDK constructs as custom constructs (if we decide to merge that feature) is simplified too
- AWS variables (CF references) and non-AWS variables (i.e. if we ever support multiprovider) are unified, or at least that's the idea (we'll see in practice when we get to it)
> Simplify variables by using CDK values directly

- README.md
- docs/database-dynamodb-single-table.md
- package.json
- src/classes/AwsProvider.ts
- src/constructs/DatabaseDynamoDBSingleTable.ts
- test/fixtures/databasesDynamoDBSingleTable/serverless.yml
- test/unit/databasesDynamoDBSingleTable.test.ts
- test/utils/@serverless__test.d.ts
This PR implements one of the use case identified in https://github.com/getlift/lift/discussions/54, the Single Table Design constructs.
The `database/dynamodb-single-table` construct deploys a single DynamoDB table with pre-configured indexes following [Single Table Design](https://www.alexdebrie.com/posts/dynamodb-single-table/) principles.
```yaml
service: my-app
provider:
name: aws
constructs:
myTable:
type: database/dynamodb-single-table
plugins:
- serverless-lift
```
On `serverless deploy`, a preconfigured DynamoDB table will be created.
The `database/dynamodb-single-table` construct creates and configures the table for production:
- a composite primary index with generic attributes names - `PK` for the partition key and `SK` for the sort key
- 5 local secondary indexes, the maximum …
> Single table construct

- README.md
- docs/serverless-types.md
- package.json
- src/plugin.ts
While YAML remains the most popular declarative syntax for Serverless service file definition - a.k.a `serverless.yml` - you can also use Javascript/Typescript definitions - i.e. `serverless.js` and `serverless.ts`. You can find more information on using JS/TS service file in the [Serverless official documentation](https://www.serverless.com/framework/docs/providers/aws/guide/intro#services).
Generated Typescript types for the service file from [@serverless/typescript](https://github.com/serverless/typescript) do NOT include `constructs` definition from Lift.
In order to cope this issue, Lift exports a type definition you can use in conjonction with the official Serverless definition:
_serverless.ts_
```ts
import type { AWS } from '@serverless/typescript';
import type { Lift } from …
```
> Add types definition for serverless.ts

- docs/permissions.md
- docs/queue.md
- docs/storage.md
- src/plugin.ts
- test/unit/permissions.test.ts
```yaml
lift:
automaticPermissions: false
```
This new option allows to opt-out from automatic permissions set up by Lift constructs.
> Allow disabling automatic permissions

- docs/static-website.md
- src/constructs/aws/StaticWebsite.ts
When provisioning Route53 records using Cloudformation, there is no way to reference distribution CNAME generated by CloudFront (even while using custom domain names).
```yml
resources:
Resources:
Route53Record:
Type: AWS::Route53::RecordSet
Properties:
HostedZoneId: XXXXX
Name: app.mydomain.
Type: A
AliasTarget:
HostedZoneId: XXXXX
DNSName: !GetAtt ???.DomainName
```
This PR adds the following variable on the `static-website` construct :
- `cname`: the domain name of the resource, such as `d111111abcdef8.cloudfront.net`
> Add cname variable for static-website construct

- docs/server-side-website.md
- docs/static-website.md
- src/classes/cloudfrontFunctions.ts
- src/constructs/aws/ServerSideWebsite.ts
- src/constructs/aws/StaticWebsite.ts
- test/unit/serverSideWebsite.test.ts
- test/unit/staticWebsites.test.ts
This PR implements redirection to a "main domain". This is especially useful for root domain to www redirections. 
The first domain will be used as the main domain where everything will redirect to if `redirectToMainDomain` is true. 
```yaml
constructs: 
website: 
type: "server-side-website"
domain: 
- www.example.com
- example.com
certificate: "arn:aws:acm:us-east-1:123456615250:certificate/0a28e63d-d3a9-4578-9f8b-14347bfe8123"
redirectToMainDomain: true
```
This will redirect every request targeting `example.com` to `www.example.com`.
I've used Cloudfront functions to do this, it seems to be the best solution for this. There are other solutions with buckets doing redirects but this feels wrong to me now that we have Cloudfront Functions available.
> feat: redirect to main domain in static and server-side websites

- src/constructs/aws/Queue.ts
Serverless' JSON schema validation should forbid users to define a "Queue" construct without a `worker` defined inside of it.
However, this schema validation isn't enforced strictly at the moment. This is the error users get in that case:
This is the most common "Lift internal error/bug" that users face (that is caused by Lift).
With this PR, users get a more explicit error:
This isn't ideal, but it improves the onboarding experience.
> Improve error message for the most common user error

- src/constructs/aws/Queue.ts
Fix #99 
This allows to use Docker images in SQS function handlers, for example:
```yaml
provider:
name: aws
ecr:
images:
my-docker-image:
path: ./
constructs:
my-queue:
type: queue
worker:
image:
name: my-docker-image
```
> #99 Support Docker images for queue handlers

- .github/ISSUE_TEMPLATE/bug.yml
- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/feature.yml
I noticed we tend to regularly ask people the same information when they create an issue, especially when requesting a new feature (what is the use-case, what config could look like, etc).
This PR introduces issue templates **forms**
This is a recent Github feature that creates an actual form which users have to fill. 
I tried to make it simple enough so that is doesn't discourages people from submitting but still give a bit more structure.
You can see a preview on my fork, feel free to create an issue there to see how it looks https://github.com/t-richard/lift/issues/new/choose
> Issue templates forms

- src/constructs/aws/StaticWebsite.ts
- test/unit/staticWebsites.test.ts
Switch the origin bucket configuration to static website hosting,
leaving the configuration on the bucket side, without having to rely
on a custom origin access identity.
Fix #163, #164
An other possible solution would be to simply re-attach a custom origin access policy with the  `s3::ListBucket` policy, as explained in [my comment](https://github.com/getlift/lift/issues/163#issuecomment-1030204356) in #163. The reason I did not implement this solution is to match lift goal on leveraging as much CDK default behaviors as possible.
If this solution is preferred, I would be happy to update the PR :slightly_smiling_face:
> Fix SPA error page behavior

- .prettierrc
- docs/queue.md
- src/constructs/aws/Queue.ts
- test/unit/queues.test.ts
I added an issue for this here https://github.com/getlift/lift/issues/160
> Queue: Add setting for maximumBatchingWindow

- src/constructs/aws/queue/sqs.ts
> Maximum number of entries per request are 10. You have sent 30.
* AWS SQS allow batches of maximum 10 entries / messages
* When retrying messages in dlq we should chunk messages in batch of 10
> fix(queue): allow retry more than 10 jobs

- .gitignore
- docs/queue.md
- package.json
- src/constructs/aws/Queue.ts
- test/unit/queues.test.ts
Extended SQS options with `encryption` and `encryptionKey` to enable Server-Side encryption. 
If `encryption` is set to `kmsManaged`, key will be managed by SQS. 
If it is set to `kms`, then `encryptionKey` will be required.
Closes #138
> Add Server-Side encryption option for SQS, fixes #138

- src/constructs/aws/SinglePageApp.ts
- test/unit/singlePageApp.test.ts
When trying to serve a pdf as a static file with the single page app contruct, the cloudfront distribution would redirect to index.html because the pdf file extension was not whitelisted. 
This PR adds the pdf file extension to the whitelist so that users can serve pdf files statically.
> feat(single-page-app): add pdf to redirect regex

- src/constructs/aws/StaticWebsite.ts
- src/constructs/aws/abstracts/StaticWebsiteAbstract.ts
- test/unit/staticWebsite.test.ts
The introduction of the single page app construct introduced a breaking change in the static website construct by removing the static website hosting.
This PR re-enables static website hosting and public read access for static buckets.
I also edited the static website tests in order to make them more strict.
Fixes https://github.com/getlift/lift/issues/192
Also see: 
- the initial issue: https://github.com/getlift/lift/issues/172
- the related PR: https://github.com/getlift/lift/pull/175
@adriencaccia
> fix(static-website): re-enable static website hosting

- docs/database-dynamodb-single-table.md
- src/constructs/aws/DatabaseDynamoDBSingleTable.ts
When working on a project with several serverless services, it is useful to get the table ARN, for instance to create a cloudformation output and use it in other services (rather than building the ARN with the table name).
> feat(single-table): expose table arn variable

- src/constructs/aws/abstracts/StaticWebsiteAbstract.ts
Follow-up of #213 which was unfortunately closed
What I need to do is parametrize some of my config:
```
constructs: {
app: {
type: 'static-website',
path: '../build',
errorPage: '404.html',
domain: '${param:domain}',
redirectToMainDomain: '${param:redirectToMainDomain}',
certificate: '${param:certificate}',
},
},
```
However if I try to setup my params with null values, they get cleaned out from stage params.
```
params: {
dev: {
domain: [],
redirectToMainDomain: false,
certificate: null, // issue here
},
production: {
domain: ['www.mywebsite.com', 'mywebsite.com'],
redirectToMainDomain: true,
certificate: 'my-certificate-arn',
},
},
```
If I do this, I get the following error:
And if I try to put the params like:
```
params: {
dev: {
domain: [],
redirectToMainDomain: false,
certificate: …
```
> feat(static-website): allow empty params

- src/constructs/aws/Webhook.ts
I have a bug on my application with Lift: I want to secure a webhook call using with a different header than Authorization (I do not have control on the header).
The HTTP request does not contain an Authorization header and thus receives a 401 error. The documentation: https://docs.aws.amazon.com/apigateway/latest/developerguide/http-api-lambda-authorizer.html
All headers are available in the event anyway, and Lift doesn't implement authorizer caching by default, so we can juste empty the `identitySource` property.
> Improve webhooks authorization

- README.md
- docs/configuration.md
- docs/serverless-types.md
- src/plugin.ts
> Exported type fix

- docs/server-side-website.md
`Comment` is defined inside the `DistributionConfig` key, not directly in the `Properties` key.
https://docs.aws.amazon.com/fr_fr/AWSCloudFormation/latest/UserGuide/aws-properties-cloudfront-distribution-distributionconfig.html
Otherwise it generates an error in Cloudformation:
> Properties validation failed for resource websiteCDN060D946D with message: #: extraneous key [Comment] is not permitted
> Fix doc about distribution comment config

- src/constructs/aws/ServerSideWebsite.ts
- test/unit/serverSideWebsite.test.ts
The goal is to prevent confusion when trying to set this up (cannot work):
```yaml
constructs:
assets:
type: server-side-website
assets:
'/*': public
```
Reported in https://github.com/brefphp/bref/discussions/1243
> Server-side website: validate asset paths

- docs/server-side-website.md
- src/constructs/aws/ServerSideWebsite.ts
I needed the created assets bucket name to reference it in a BucketPolicy. So I've exposed the bucketname as a variable (like in the storage construct)
> Expose bucketName variable in server-side-website

- src/constructs/aws/ServerSideWebsite.ts
> fix: Remove manual construction of cloudfront function name to avoid max length constraint

- src/constructs/aws/ServerSideWebsite.ts
- src/constructs/aws/SinglePageApp.ts
- src/constructs/aws/StaticWebsite.ts
- src/constructs/aws/abstracts/StaticWebsiteAbstract.ts
- src/utils/naming.ts
- test/unit/serverSideWebsite.test.ts
- test/unit/singlePageApp.test.ts
- test/unit/staticWebsite.test.ts
- test/unit/utils/naming.test.ts
Fix #247, i.e. another approach to fix #242 after #245.
Instead of letting CloudFormation generate the CF function names, we hardcode them and trim them if they go beyond the 64 characters limit.
> Fix #247, #242 Trim CloudFront function names to stay under the limit

- docs/queue.md
- src/constructs/aws/Queue.ts
References Issue #188 
Changes aimed at allowing a worker to be assigned as a handler to the dead letter queue. Also publishing the dlq ARN to the yaml file - similar to how the main queue ARN 
Reasons:
* It was difficult to add a worker to a DLQ compared to how easy it was to add one to the main queue
* It would have required manually inserting the ARN into the YAML after having created the queue
* Allowing additional manipulation of the DLQ due to exposure of it's ARN in the YAML file
> Allow attachment of worker to Dead-letter queue

- docs/server-side-website.md
- src/constructs/aws/ServerSideWebsite.ts
- test/unit/serverSideWebsite.test.ts
CloudFront added a new `AllViewerExceptHostHeader` policy: https://twitter.com/cristiangraz/status/1628585607479050240
This is exactly what we needed!
We can get rid of:
- our custom "origin policy" (it was needed to avoid forwarding the Host header)
- our custom "cache policy" (it was needed to forward the Authorization header)
We gain:
- less code for us
- less config for users 🎉
- less resources to deploy, meaning faster deployments 🎉
- users don't have to choose or configure the headers they want to forward 🎉
- users are no longer limited by the limit of 10 forwarded headers 🎉
If you were setting the `forwardedHeader` config in `serverless.yml` to add more headers to forward, you can now safely remove this option:
```yaml
constructs:
website:
forwardedHeaders:
- Accept
- …
```
> Simplify server-side-website with the new AllViewerExceptHostHeader policy

- test/unit/permissions.test.ts
Serverless v3.28.0 updates permissions given to lambda to be able to use a new logs:TagResource action on Cloudwatch groups. Rewriting the test to ensure no permission regarding s3 are added to lambda instead of checking exact Action match assertions, in order to have tests passing both for serverless v2 and latest v3
PR made on Serverless v3.28.0 that introduce this change : https://github.com/serverless/serverless/pull/11766
> Rewrite disable auto permission test

- docs/single-page-app.md
- docs/static-website.md
- src/constructs/aws/abstracts/StaticWebsiteAbstract.ts
Hi,
Similar to #241, exposing the assets bucket name for the static website and spa constructs.
My use case:
I want to trigger an event after objects are created in the bucket so a Lambda can add some metadata to each file uploaded in that folder (Cache Control headers etc...)
> Expose assets bucket name to static-website and single-page-app

- src/constructs/aws/SinglePageApp.ts
- test/unit/singlePageApp.test.ts
Hi,
AWS has updated their list of extensions excluded from redirections in SPA, this PR updates the list to match AWS' (adding the webp extension) and also adds the avif extension.
This allows developers using lift's SPA construct to use .webp and .avif images. Currently it will redirect to /index.html and not display the image.
See: https://docs.aws.amazon.com/amplify/latest/userguide/redirects.html#redirects-for-single-page-web-apps-spa
> Add webp and avif exceptions to CF request function

- docs/queue.md
Content based deduplication MUST be explicitly disabled to support sending deduplication IDs. I've been hunting down a bug for months trying to figure out what's going wrong. Setting a deduplication ID with content based deduplication enabled does nothing - it still uses the body.
> Correct misleading deduplication documentation

- src/constructs/aws/ServerSideWebsite.ts
- test/unit/serverSideWebsite.test.ts
Update the `server-side-website` construct to include support for HTTP/3
> Enable HTTP/3 support on CloudFront

- src/constructs/aws/SinglePageApp.ts
- test/unit/singlePageApp.test.ts
https://github.com/getlift/lift/issues/331
Currently wasm files are not loaded properly as the CloudFront function redirects them to .html. Adding wasm to redirect regex fixes this and wasm files are loaded properly.
> Add wasm to redirect regex getlift/lift#331

- .github/workflows/ci.yml
- package.json
Allow the usage under Node 20.
The CI worked here:
https://github.com/dnp1/lift/actions/runs/5155713648
> Allow the usage under Node 20.

- src/classes/cloudfrontFunctions.ts
We've run into issues with dynamic configs which are stage-dependent - different stages have different domain(s).
This change allows the directive to be present but will silence its behaviour where only a single domain has been specified.
> Gracefully handle redirectToMainDomain with only a single domain

- src/constructs/aws/DatabaseDynamoDBSingleTable.ts
Closes #339 
Without this IAM permission, transacted writes in dynamodb using the `ConditionCheck` feature are disallowed.
See:
https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_ConditionCheck.html
https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/transaction-apis-iam.html
Example usage:
After this change you would be able to make use of ConditionCheck in transacted writes e.g.
```ts
client.send(
new TransactWriteCommand({
TransactItems: [
// checks an item condition is successful
{
ConditionCheck: {
TableName: environment.tableName,
Key: {
PK: 'somepk',
SK: 'somesk',
},
ConditionExpression: 'attribute_exists(PK)',
},
},
// and writes a record in 1 transaction ensuring consistency
{
Put: {
TableName: environment.tableName,
Item: someItem,
},
}
]
}));
```
> fix: adds `dynamodb:ConditionCheckItem` permission to dynamodb construct

- src/constructs/aws/Queue.ts
- test/unit/queues.test.ts
https://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/sqs-monitoring-using-cloudwatch.html
> When an Amazon SQS queue is inactive for more than six hours, the Amazon SQS service is considered asleep and stops delivering metrics to the CloudWatch service. Missing data, or data representing zero, can't be visualized in the CloudWatch metrics for Amazon SQS for the time period that your Amazon SQS queue was inactive.
Because of this, the DLQ alarms currently created by lift will show `Insufficient data` most of the time when the queue they monitor are empty _and inactive_.
This PR sets `treatMissingData` to `notBreaching` on the alarm vs the current CDK default of `missing`. `notBreaching` will allow an inactive (and thus empty) SQS queue to show `Ok` when browsing …
> SQS DLQ alarm should treat missing data as not breaching

- docs/webhook.md
- src/constructs/aws/Webhook.ts
- test/fixtures/webhooks/serverless.yml
- test/unit/webhooks.test.ts
Some webhooks utilise PUT instead of strictly POST, in order to support them I've added in the ability to specify which method the webhook should allow in order to allow for these cases
Let me know if you want any changes to this, it's my first time touching the project so suggestions are more than welcome
> Add in method setting for webhooks

- src/constructs/aws/ServerSideWebsite.ts
- src/providers/AwsProvider.ts
- test/unit/serverSideWebsite.test.ts
This PR attempts to solve https://github.com/getlift/lift/issues/364. The issue is that the stage needs to be appended to the URL in REST scenario in order to view the deployed app. By using [`originPath`](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-cloudfront-distribution-origin.html#:~:text=%3A%20No%20interruption-,OriginPath,Update%20requires%3A%20No%20interruption,-OriginShield) of the CloudFront distribution we can hide it from the user so he can simply access the CloudFront URL/custom domain.
This is my first time working on a serverless plugin so I hope I used the correct approach. Please me know if I should change anything.
> fix: hide stage in URL in REST scenario

- src/constructs/aws/StaticWebsite.ts
Fixes #320 
Since april 2023, AWS S3 enforces two new default bucket security settings by automatically enabling S3 Block Public Access and disabling S3 access control lists (ACLs) for all new S3 buckets
This hotfix adds missing required BlockPublicAccess configuration.
Deploy this stack and error is thrown.
```yaml
service: demo
provider:
name: aws
region: eu-west-3
stage: prod
plugins:
- serverless-lift
constructs:
demo:
type: static-website
path: dist
```
> Add BlockPublicAccess required config

- src/utils/s3-sync.ts
S3 has a batch delete limit of 1000 files.
The PR introduces chunking `keysToDelete` into batches of 1000 files to bypass the limitation.
> Chunk deleted files into batches

- src/constructs/aws/ServerSideWebsite.ts
Hi there,
With the release of Serverless 4, it appears that the ServerlessUtils `progress.create()` method now requires an initial argument to be passed. This is causing issues during deployment and any other time the `uploadAssets()` function is called.
Steps to Reproduce:
- Use Lift's ServerSideWebsite with Serverless 4.
- Trigger deployment or any action that calls the `uploadAssets` function.
- Observe the error due to the missing argument for `progress.create()`.
Proposed Fix: Update the `uploadAssets()` function in ServerSideWebsite to pass an initial argument to `progress.create()` as follows:
```js
uploadProgress = progress.create({
message: 'Uploading assets'
});
```
Current Code Reference:
https://github.com/getlift/lift/blob/08772c56cc219ca7fa65cc4ff7c4dfea20246a70/src/construct …
> ServerSideWebsite: Add Progress.create() arg for Serverless 4 compatibility

- .github/workflows/ci.yml
- jest.config.js
- src/constructs/aws/ServerSideWebsite.ts
- test/unit/staticWebsite.test.ts
I noticed that the tests were failing, I believe this PR should fix the tests.
> Fixing tests

- package.json
- src/constructs/aws/ServerSideWebsite.ts
- src/constructs/aws/Webhook.ts
- test/unit/serverSideWebsite.test.ts
- test/unit/singlePageApp.test.ts
- test/unit/staticWebsite.test.ts
> TypeError: Cannot read properties of undefined (reading 'originRequestPolicyId')
> Upgrade CDK and fix following their breaking change
